### ISSUE TITLE
BUG: browser window left open has many error msgs

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#340] opened 2020-12-04 07:30 UTC
**Describe the bug**
On leaving a window open and coming back see the following box:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/201c83f1-8b69-4593-8d94-ce40def6e59c)

**To Reproduce**

**Comment by OlegSubik** [comment] 2020-12-08 14:32
should be fixed after merge of #318

**Comment by Comoque1** [comment] 2020-12-14 12:51
The issue is not reproducible anymore with branch "Client.Web" "clean-up-lint"

**Closed by Comoque1** 2020-12-14 12:51 UTC
Labels: bug, client
